---
- name: Verificar si los puertos TCP están abiertos en el host remoto
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    puertos_objetivo: [22, 80, 443]
    protocolo_objetivo: "tcp"

  tasks:
    - name: Validar que el protocolo especificado sea solo TCP
      ansible.builtin.assert:
        that:
          - protocolo_objetivo == 'tcp'
        fail_msg: "Este playbook solo soporta verificación TCP por limitaciones del módulo wait_for."
        success_msg: "Protocolo TCP aceptado."

    - name: Verificar puertos TCP abiertos
      ansible.builtin.wait_for:
        port: "{{ item }}"
        timeout: 3
        state: started
        host: "{{ inventory_hostname }}"
      loop: "{{ puertos_objetivo }}"
      register: resultado_puertos
      ignore_errors: yes

    - name: Construir lista de resultados por puerto
      ansible.builtin.set_fact:
        puertos_estado: >-
          {{
            puertos_estado | default([]) + [{
              'puerto': item.item,
              'estado': ('ABIERTO' if not item.failed else 'CERRADO')
            }]
          }}
      loop: "{{ resultado_puertos.results }}"

    - name: Mostrar resultado por puerto
      ansible.builtin.debug:
        msg: "Puerto {{ item.puerto }}/tcp está {{ item.estado }}"
      loop: "{{ puertos_estado }}"

    - name: Mostrar resumen final
      ansible.builtin.debug:
        msg: |
          Resultado final de verificación de puertos en {{ inventory_hostname }}:
          {% for p in puertos_estado %}
          - Puerto {{ p.puerto }}/tcp: {{ p.estado }}
          {% endfor %}

